### ISSUE TITLE
Gelpia compilation errors

### ISSUE THREAD

**Issue by ggeorgakoudis** [soarlab/FPTuner#3]
Hello,

First of all, many thanks for the excellent paper and sharing the work through this repo.

I'm trying to build FPTuner in an Ubuntu 16.04. I get the following errors related to building Gelpia.

1. "make requirements" fails: the url (http://lipforge.ens-lyon.fr/frs/download.php/162/crlibm-1.0beta4.tar.gz) to download CRLibM is broken 

2. I bypassed problem 1. by using the crlibm.tar.gz from the develop branch of Gelpia and have succesfully built requirements. However,  compilation of Gelpia ("make") fails  with an error related to Rust and the getopts package:

error[E0301]: cannot mutably borrow in a pattern guard
   --> /home/ggeorgak/.cargo/registry/src/github.com-1ecc6299db9ec823/getopts-0.2.17/src/lib.rs:405:73
    |
405 |                         } else if was_long || name_pos < names.len() || args.peek().map_or(true, |n| is_arg(&n)) {
    |                                                                         ^^^^ borrowed mutably in pattern guard

error: aborting due to previous error

error: Could not compile `getopts`.

**Comment by keram88** [comment]
Thank you for trying our tool.
I think I fixed the issue by pinning the versions of Rust dependencies. Also, thank you for pointing out the missing CRLibM library in that branch.

Can you try a `make clean` and try building again?

Best,
Mark

**Comment by ggeorgakoudis** [comment]
Thank you, Mark. Your fix works.

**Comment by zvonimir** [comment]
@keram88 Was this resolved? If so, then please close it.

**Comment by keram88** [comment]
Yes. I was waiting for confirmation.

**Comment by lam2mo** [comment]
For anyone who is visiting this later, I encountered this issue on RHEL7 as well, and the fix noted above did not seem to be sufficient. However, adding some extra braces to the indicated Rust source file as described [here](https://github.com/rust-lang/rust/issues/37510) does seem to have fixed the compilation problem.

**Comment by zvonimir** [comment]
@keram88 : could you please revisit this based on the above comment?
Thanks @lam2mo!
